### ISSUE TITLE
PiNet Stretch status

### ISSUE THREAD

**Issue by gbaman** [PiNet/PiNet#142]
Given I have had a few questions over the past while on "Where is PiNet Stretch?" and "Why does PiNet still used Jessie instead of Stretch?", this issue is here to include the status of the PiNet Stretch release.

So far, the main code for PiNet Stretch is complete and can be found over on the [Stretch-Alpha](https://github.com/PiNet/PiNet/tree/stretch-alpha) branch. 
There are though a few parts left
- ~~The main bug left is in some random cases, [LDM](http://manpages.ubuntu.com/manpages/trusty/man1/ldm.1.html), which handles the login screen seems to crash and leave a black and unresponsive screen up. In most cases this is resolved with a reboot, but it is too frequent current to allow the PiNet Stretch release to go ahead.~~ - Maybe fixed? - https://github.com/PiNet/PiNet/commit/0688df42214c67cda061ac39ae9d96f3b01b54e0

- ~~Sonic Pi takes a very long time to startup (around 90s on a Pi 3B+). This needs fixed before PiNet Stretch can go ahead.~~

- ~~A startup issue is causing what looks like a timeout before it starts booting Raspbian, adding maybe 20s to startup~~. - Fixed - https://github.com/PiNet/PiNet/commit/7fde8a803f2d249d9d0a7e1909d4096307069ca7

- ~~By default Raspbian now disables the "Places" menu in PCManFM. PiNet needs this back as it is far more user friendly (and supports flash drives etc)~~ - Fixed - https://github.com/PiNet/PiNet/commit/2de679e839e715e985371084c3d61a32bd3f2162

-  ~~There seems to be random issues with the package holding around kernels etc still, with newer versions being installed then apt refusing to downgrade them when needed. Ideally the newer versions shouldn't be installed in the first place. This is in relation to apt package holding~~ Seems to be fixed...

- ~~Migration system needs built to allow in place or rebuild migration for Jessie-->Stretch.~~ - Done - https://github.com/PiNet/PiNet/commit/6a432d790ea5f1448ec0c43a228f005d36ea34c7

- The "migration from Jessie" code is completed, but needs extensive testing on both methods (complete rebuild or inplace upgrade).

- The new initramfs tools startup menu system needs integrated into the PiNet boot files build system. 

- ~~LTSP itself isn't formally supporting Ubuntu 18.04 just yet. Last I heard they are saying they hope to be ready by September. I am not 100% sure which of the above may be broken by some of their code.~~

- ~~PiNet control panel application on teacher accounts can't be launched from the Raspberry Pis. May be an issue with gnome-terminal or ltsp-remoteapps.~~ - Fixed - https://github.com/PiNet/PiNet/commit/9f0ccc73941823e347339f1be2fc55d09ad22f7c

- In some cases, the Raspberry Pis don't shut down correctly and get stuck. This can especially be an issue with automatic kernel/boot files being pushed out. Perhaps may be related to the odd behaviour the Pi can show with halt vs shutdown. Needs further investigation.

Unfortunately all of the above is simply taking much longer than expected due to my time being far more limited now than it was a few years back.

I will keep this Github issue up to date with the PiNet Stretch status as more gets completed.

## Testing
Want to test out PiNet Stretch? The install process isn't that much different to normal PiNet. Note this must be done on a completely fresh install of Ubuntu 16.04. Migration is not yet complete.
1. ```wget https://raw.githubusercontent.com/PiNet/PiNet/stretch-alpha/pinet```
2. ```wget https://raw.githubusercontent.com/PiNet/PiNet/stretch-alpha/Scripts/pinet_functions_python.py```
3. ```sudo mv pinet_functions_python.py /usr/local/bin/```  
4. ```echo "ReleaseChannel=alpha" | sudo tee /etc/pinet```
5. ```sudo bash pinet```

Feel free to post any feedback on the process below.

**Comment by gbaman** [comment]
Glad to say the LDM bug is now sorted, allowing the main testing start properly - https://github.com/PiNet/PiNet/commit/0688df42214c67cda061ac39ae9d96f3b01b54e0

**Comment by mcolliver** [comment]
Having tried the instructions above I think line 2 needs to be (as this now seems to work for me):

`wget https://raw.githubusercontent.com/PiNet/PiNet/stretch-alpha/Scripts/pinet_functions_python.py`

**Comment by gbaman** [comment]
Whoops, good catch @mcolliver, it was needed to still be pulled from the Jessie branch initially, but now the Python code is caught up, the Stretch version is needed as well. 
Have now changed, thanks.

**Comment by gbaman** [comment]
I can now confirm another bug has been fixed. This case, was related to the file manager (PCManFM).
Raspberry Pi Trading switched over (using a raspberrypi-ui-mods update) to "simplified" mode for the file manager. Although it simplified the UI a little, it also removed the "Places" sidebar, replacing it will a full system tree.
This made accessing removable drives (like micro:bits etc) very difficult and shared folders as well.

Pictures - https://twitter.com/gbaman1/status/1026459946727206913

Fixed so now sets the config option back.

https://github.com/PiNet/PiNet/commit/2de679e839e715e985371084c3d61a32bd3f2162


Still plenty more bugs unfortunately though blocking PiNet Stretch.

**Comment by bbinet** [comment]
@gbaman thanks for the status update.
Could you share the list of existing stretch bugs you are aware of?

**Comment by gbaman** [comment]
@bbinet I have updated the initial comment with some of the bugs I am aware of currently, but there is likely to be others missing that I have yet to come across.

**Comment by gbaman** [comment]
And there is another issue fixed, the slow startup issue was related to LTSP trying to fetch an lts.conf from tftp when the tftp server wasn't actually running (or generally used with PiNet).
Now fixed in https://github.com/PiNet/PiNet/commit/7fde8a803f2d249d9d0a7e1909d4096307069ca7.

**Comment by bbinet** [comment]
@gbaman thanks for the updated list of bugs remaining in stretch, this is good to know before switching.

**Comment by gbaman** [comment]
Fixed a few bugs this weekend including
- raspberrypi-ui-mods overwriting PiNet configs (desktop backgrounds for example).
- Unable to launch PiNet from teacher accounts on the Pi.
- A few Ubuntu 18.04 bugs.

At this stage, mainly just leaves the new boot menu code integrating into the kernels build process, fixing Sonic Pi startup times which will probably need advice from @samaaron, (potential, but unreproducable audio playback issues) and then testing of the migration system.
